# Generated by Django 5.1.3 on 2025-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
